name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Set up environment variables
      run: echo "$GCP_SA_KEY" > /tmp/key.json
      env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate to GCP
      run: gcloud auth activate-service-account --key-file=$GCP_SA_KEY

    # Add more steps to deploy your application
