name: Deploy DAG

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-storage
        
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Upload DAG to GCS
      run: |
        gsutil cp dags/ecommerce_insights_dag.py gs://europe-west1-deng-capstone--2a44b3bb-bucket/dags/