name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Write GCP Service Account Key to a file
      run: echo "${{ secrets.GCP_SA_KEY }}" | jq . > /tmp/key.json

    - name: Authenticate to GCP
      run: gcloud auth activate-service-account --key-file=/tmp/key.json

    - name: Deploy to App Engine
      run: gcloud app deploy --quiet

