name: Hello World Workflow

on:
  push:
    branches:
      - main  # Run only on pushes to the 'main' branch
      
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello, World!"